# Generated by Django 3.2.13 on 2022-06-13 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saybook', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
